relativeURLs = "true"
languageCode: en-us
defaultContentLanguage: en-us
title: Frédéric Silvestre's Blog
theme: hugo-tranquilpeak-theme
disqusShortname: hugo-tranquilpeak-theme
paginate: 7
canonifyurls: yes
permalinks:
  post: /:year/:month/:slug/
taxonomies:
  archive: archives
  category: categories
  tag: tags
author:
  bio: My name is Frédéric, and I'm a professor of biology at the University of Namur in Belgium. This blog is all about sharing my passion about science, zoology, traveling, photography, videography, and outdoor activities. 
  job: Professor of Biology at the University of Namur
  location: Belgium
  name: Frédéric Silvestre's Blog
  picture: "/img/avatar1.jpg"
  
menu:
  links:
    - identifier: github
      name: GitHub
      pre: <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      url: https://github.com/fredsilvestre
      weight: 4
    - identifier: twitter
      name: Twitter
      pre: <i class="sidebar-button-icon fa fa-lg fa-twitter"></i>
      url: https://twitter.com/fsilvestrelab
      weight: 1
    - identifier: instagram
      name: Instagram
      pre: <i class="sidebar-button-icon fa fa-instagram"></i>
      url: https://www.instagram.com/fsilvestrephoto/
      weight: 2
    - identifier: flickr
      name: flickr
      pre: <i class="sidebar-button-icon fa fa-flickr"></i>
      url: https://www.flickr.com/photos/fsilvestrephoto/albums
      weight: 3


  main:
    - identifier: home
      name: Home
      pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      url: /
      weight: 1
    - identifier: categories
      name: Categories
      pre: <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      url: /categories
      weight: 2
    - identifier: tags
      name: Tags
      pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      url: /tags
      weight: 3
    - identifier: archives
      name: Archives
      pre: <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      url: /archives
      weight: 4
    - identifier: about
      name: About
      pre: <i class="sidebar-button-icon fa fa-lg fa-address-card"></i>
      url: /#about
      weight: 5
    - identifier: search
      name: Search
      pre: <i class="sidebar-button-icon fa fa-lg fa-search"></i>
      url: /#search
      class: st-search-show-outputs
      weight: 6
  misc:
    - identifier: rss
      name: RSS
      pre: <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
      url: /index.xml
      weight: 1
params:
  autoThumbnailImage: yes
  clearReading: yes
  coverImage: images/DeathValley.png
  description: Frédéric Silvestre's Blog
  header:
    rightLink:
      class: 'open-algolia-search'
      icon: 'search'
      url: /#search
  hierarchicalCategories: false
  imageGallery: yes
  sharingOptions:
    - icon: fa-facebook-official
      name: Facebook
      url: https://www.facebook.com/sharer/sharer.php?u=%s
    - icon: fa-twitter
      name: Twitter
      url: https://twitter.com/intent/tweet?text=%s

  sidebarBehavior: 1
  syntaxHighlighter: highlight.js
  thumbnailImage: yes
  thumbnailImagePosition: bottom
